### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by chrisdrackett** [coreyleelarson/react-typekit#1]
I see the screen tag in my HTML, but I don't see any calls being made to typekit and also don't see my fonts

**Comment by coreyleelarson** [comment]
Can you please post some code examples?

**Comment by chrisdrackett** [comment]
I'm just following the readme. I see the script in my HTML on inspection, but I don't see any calls being made to typekit

**Comment by coreyleelarson** [comment]
I am assuming your application is not a universal/isomorphic application, in which case the script I was injecting was not getting executed for some reason. I never had this problem as my application is primarily server-side rendered.

I have made some changes to ensure the script is executed in both server-rendered and non-server-rendered contexts.

Try v1.0.4 and see if that resolves your issue.

**Comment by coreyleelarson** [comment]
I am assuming your application is not a universal/isomorphic application, in which case the script I was injecting was not getting executed for some reason. I never had this problem as my application is primarily server-side rendered.

I have made some changes to ensure the script is executed in both server-rendered and non-server-rendered contexts.

Try v1.0.6 and see if that resolves your issue.
