### ISSUE TITLE
Forbidden code point U+0008 fails HTML5 validation

### ISSUE THREAD

**Issue by ZLevine** [coreyleelarson/react-typekit#2]
This plugin causes a page to fail W3C HTML5 validation because it contains forbidden code point (`BS` character) `U+0008`.

To recreate:
- Run any site using this plugin through [the validator](https://validator.w3.org/nu/).
- Observe the error

I see the `\b` character in use in `buildScript.js` (both src/utilities and lib/utilities):

```javascript
h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";
```

**Comment by coreyleelarson** [comment]
@ZLevine Interesting, because that snippet of code was copied directly from Adobe Typekit's documentation. I'll look into it and get back with you later today.

**Comment by coreyleelarson** [comment]
@ZLevine Try out `1.1.3` and let me know if that fixes it. Looks like `\b` is used by Typekit for RegExp purposes, but the browser was reading as a backspace character. I just had to escape the backslash, and the validation error disappeared on my test app.

**Comment by ZLevine** [comment]
@coreyleelarson Verified this fixes the issue. Thanks!!
