### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by haniotis** [coreyleelarson/react-typekit#3]
Getting this error after adding the `<Typekit>` component to my Layout:

```bash
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

It's highly likely that I just didn't put it in the right place :)

**Comment by coreyleelarson** [comment]
Do you have an example I can look at?

**Comment by coreyleelarson** [comment]
I'm going to go ahead and close this issue, assuming you figured out your issue. If you're still having an issue, feel free to reopen.
